#!/bin/sh
SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
saved_stty=$(stty -g 2>/dev/null)
java $SBT_OPTS -jar `dirname $0`/bin/sbt-launch.jar "run $@"
stty $saved_stty

